name: Automated Run

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
  
jobs:
  run-and-recur:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write 

    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'schedule' && github.event.workflow_run.conclusion == 'success')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create dataset directory
        run: mkdir -p dataset

      - name: Create or check for tt2_players.csv
        run: |
          if [ ! -f "dataset/tt2_players.csv" ]; then
            echo 'User ID,Enkord account full name,Registered' > dataset/tt2_players.csv
          fi
          
      - name: Scraping Missing IDs
        run: python main.py --mode missing

      - name: Scraping Anonymous IDs
        run: python main.py --mode anonymous

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automated: Update tt2_players.csv with new data"
          file_pattern: "dataset/tt2_players.csv"
      
      - name: Trigger next run after 5 minutes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Starting a 5-minute timer before triggering the next run..."
          sleep 300  # Wait for 300 seconds (5 minutes)
          echo "Triggering the next workflow run..."
          gh workflow run run.yml --ref ${{ github.ref }}
